"""add_flutterwave_to_payment_config

Revision ID: 20ab4b39a674
Revises: 655de074c9d9
Create Date: 2026-03-31 03:04:10.516578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ab4b39a674'
down_revision: Union[str, Sequence[str], None] = '655de074c9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_config', sa.Column('flutterwave_public_key', sa.String(), nullable=True))
    op.add_column('payment_config', sa.Column('flutterwave_secret_key', sa.String(), nullable=True))
    op.add_column('payment_config', sa.Column('flutterwave_encryption_key', sa.String(), nullable=True))
    op.add_column('payment_config', sa.Column('flutterwave_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_config', 'flutterwave_enabled')
    op.drop_column('payment_config', 'flutterwave_encryption_key')
    op.drop_column('payment_config', 'flutterwave_secret_key')
    op.drop_column('payment_config', 'flutterwave_public_key')
    # ### end Alembic commands ###
