"""add_payment_config

Revision ID: 655de074c9d9
Revises: c4565f9d52b6
Create Date: 2026-03-31 02:52:26.727731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655de074c9d9'
down_revision: Union[str, Sequence[str], None] = 'c4565f9d52b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stripe_public_key', sa.String(), nullable=True),
    sa.Column('stripe_secret_key', sa.String(), nullable=True),
    sa.Column('stripe_webhook_secret', sa.String(), nullable=True),
    sa.Column('stripe_enabled', sa.Boolean(), nullable=True),
    sa.Column('cinetpay_api_key', sa.String(), nullable=True),
    sa.Column('cinetpay_site_id', sa.String(), nullable=True),
    sa.Column('cinetpay_enabled', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_account_holder', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_iban', sa.String(), nullable=True),
    sa.Column('bank_swift', sa.String(), nullable=True),
    sa.Column('bank_instructions', sa.Text(), nullable=True),
    sa.Column('bank_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_config')
    # ### end Alembic commands ###
